apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app.name}}
  namespace: {{app.namespace}}
  labels:
    team: {{app.team}}
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/internal/live"
    initialDelay: 3
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "/internal/live"
    initialDelay: 3
    timeout: 1
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: SELF_URL
      value: {{ingress}}
    - name: PEN_APPLICATION
      value: {{pen.application}}
    - name: PEN_URL
      value: {{pen.url}}
  accessPolicy:
    outbound:
      external:
        - host: graph.microsoft.com
        - host: login.microsoftonline.com
        - host: pensjon-pen-q2.dev-fss-pub.nais.io
  azure:
    application:
      tenant: {{azure.tenant}}
      enabled: true
      claims:
        groups:
          - id: {{azure.grupper.drift}}
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
