
export enum Sakstyper {
  AFP = "AFP",
  AFP_PRIVAT = "AFP Privat",
  ALDER = "Alderspensjon",
  BARNEP = "Barnepensjon",
  FAM_PL = "Familiepleierytelse",
  GAM_YRK = "Gammel yrkesskade",
  GENRL = "Generell",
  GJENLEV = "Gjenlevendeytelse",
  GRBL = "Grunnblanketter",
  KRIGSP = "Krigspensjon",
  OMSORG = "Omsorgsopptjening",
  UFOREP = "Uføretrygd",
}

export enum Vedtakstyper {
  AFPEO = "AFP-etteroppgjør",
  ANKE = "Anke",
  AVSL = "Avslag",
  ENDRING = "Endring",
  ERSTATNING = "Erstatning",
  ETTERGIV_GJELD = "Ettergivelse av gjeld",
  FORGANG = "Førstegang",
  FRYS = "Frys",
  GOMR = "G-omregning",
  INTERNKON = "Internkontroll",
  KLAGE = "Klage",
  MTK = "Merskatt tilbakekrevning",
  OMGJ_TILBAKE = "Omgjøring av tilbakekreving",
  OPPHOR = "Opphør",
  OPPTJ = "Opptjening",
  SAK_OMKOST = "Saksomkostninger",
  SAMMENSTOT = "Sammenstøt",
  TILBAKEKR = "Tilbakekreving",
  UT_VURDERING_EO = "Vurdering av etteroppgjør",
  UTSEND_AVTALELAND = "Utsendelse til avtaleland",
}
